Miodrag/20190117 m71 python
webrtc-uwp/webrtc-windows-apis pull request #9
Opened 2019-01-20 19:11 UTC by miodrag

Implemented/modified external audio device in m71.

2019-01-20 19:14 UTC, robin-raymond requested changes
This appears to be requesting to merge to master; we can't do that as it must be merged into releases/m71 and not direct to master.

2019-01-20 19:44 UTC, miodrag commented
The only merge combination that exposes only the files I changed is the merge `Sergej/20181206-m71-python` because that was the base point to create my branch. I hope that this is correct choice for this pull-request.

2019-01-20 19:50 UTC, robin-raymond approved these changes
I'd like @morosev to review as well.

2019-01-21 12:45 UTC, morosev requested changes

2019-01-21 12:45 UTC, morosev commented on windows/wrapper/impl_webrtc_AudioDeviceWasapi.cc
> +		  playoutEnabled_(true),
Tabs instead of spaces...

2019-01-21 12:45 UTC, morosev commented on windows/wrapper/impl_webrtc_AudioDeviceWasapi.cc
> +
Fix tabs.

2019-01-21 12:45 UTC, morosev commented on windows/wrapper/impl_webrtc_AudioDeviceWasapi.h
> +			bool                                    playoutEnabled_;
Tabs...

2019-01-21 12:45 UTC, morosev commented on windows/wrapper/impl_webrtc_IAudioDeviceWasapi.h
> +			bool playoutEnabled_;
Already defined in inherited class AudioDeviceWasapi.

2019-01-21 18:08 UTC, morosev approved these changes

2019-01-22 08:31 UTC, merged